### ISSUE TITLE
Dimension of PE 

### ISSUE THREAD

**Issue by ccmmKK** [CGT-ICLR2020/CGT-ICLR2020#1]
There are two comments in the model.py confused me:

```
class Encoder(nn.Module):
    ...
    def forward(self, x_d, x_pe, graph, return_attns=False):
        ...
        :param x_pe: position encoding, shape: (b, t, 6)
        ...
        #  get position encoding, pe: (B,T) f 0-3 periodicty, 4 trend qk, 5 trend v

        inputs = x_d.repeat(1, 1, 1, self.pe_dim)  # (b, v, t, 5)
        inputs = (inputs.permute(1, 0, 2, 3).contiguous() + x_pe).permute(1, 0, 2, 3).contiguous()  # (b, v, t, f)
```

Why the shape of x_pe is `(b, t, 6)`? Isn't it `(b, t, 5)` like what is shown in the Figure 3 of your paper?

What's the meaning of `pe: (B,T) f 0-3 periodicty, 4 trend qk, 5 trend v`? 

If the shape of input is `x_d: (b, v, t, f)` and `f=1`, why the shape of inputs is `(b, v, t, f) ` at the last line of the code shown above?

Waiting for your response ~~~ Thx ~~~

**Comment by CGT-ICLR2020** [comment]
x_pe is (b,t,5)
We need to clarify and rectify these comments. Some of them are wrong. Sorry for the inconvenience.
